spring:
  profiles:
    active: mariadb

spring.batch.job.names: ${job.name:NONE}

---
#spring:
#  profiles: local
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver
#  batch:
#    jdbc:
#      initialize-schema: always
---
spring:
  profiles: mariadb
  datasource:
   hikari:
    driverClassName: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/libaryproject
    username: root
    password: 1234
  batch:
    job:
      enabled: true
      names: ${job.names:NONE}
    jdbc:
      initialize-schema: always
      table-prefix: SYSTEM_